/* Copyright (C) YOOtheme GmbH, YOOtheme Proprietary Use License (http://www.yootheme.com/license) */

(function(c){tinymce.PluginManager.requireLangPack("widgetkit");tinymce.create("tinymce.plugins.WidgetkitPlugin",{init:function(b,a){b.addCommand("mceWidgetkit",function(){c.topbox.show("Loading...",{title:"Insert Widgetkit widget",buttons:{Insert:function(){var a=c("#widgetkit_select_box").val();""!=a&&(a="[widgetkit id="+a+"]","undefined"!=typeof tinyMCE&&!b.isHidden()&&(b.focus(),tinymce.isIE&&b.selection.moveToBookmark(tinymce.EditorManager.activeEditor.windowManager.bookmark),b.execCommand("mceInsertContent",
!1,a)),this.close())},Cancel:function(){this.close()}}});c.topbox.box.find(".topbox-button:first").hide();c.post(widgetkitajax+"&task=editor",{},function(a){c.topbox.setContent(a);c.topbox.box.find(".topbox-button:first").show()})});b.addButton("widgetkit",{title:"Add Widgetkit widget",cmd:"mceWidgetkit",image:a.replace("/js","/images/widgetkit_32.png")});b.onNodeChange.add(function(a,c,b){c.setActive("example","IMG"==b.nodeName)})},createControl:function(){return null},getInfo:function(){return{longname:"Widgetkit Worpdress TinyMCE Button",
author:"yootheme",authorurl:"http://www.yootheme.com",infourl:"http://www.yootheme.com",version:"1.0"}}});tinymce.PluginManager.add("widgetkit",tinymce.plugins.WidgetkitPlugin)})(jQuery);
(function(c){var b=null;c.topbox=b={box:null,options:{},persist:!1,show:function(a,d){this.box&&this.clear();this.options=c.extend({title:!1,closeOnEsc:!0,cls:"",width:400,height:"auto",speed:500,easing:"swing",buttons:!1,beforeShow:function(){},onShow:function(){},beforeClose:function(){},onClose:function(){}},d);var e='<div class="topbox-window '+b.options.cls+'">';this.box=c(e+'<div class="topbox-closebutton"></div><div class="topbox-title" style="display:none;"></div><div class="topbox-content"><div class="topbox-innercontent"></div></div><div class="topbox-buttonsbar"><div class="topbox-buttons"></div></div></div>');
this.box.find(".topbox-closebutton").bind("click",function(){b.close()});if(this.options.buttons){var f=this.box.find(".topbox-buttons");c.each(this.options.buttons,function(a,d){c('<span class="topbox-button">'+a+"</span>").bind("click",function(){d.apply(b)}).appendTo(f)})}else this.box.find(".topbox-buttonsbar").hide();"auto"!=b.options.height&&this.box.find(".topbox-innercontent").css({height:b.options.height,"overflow-y":"auto"});this.setContent(a).setTitle(this.options.title);this.box.css({opacity:0,
visibility:"hidden",left:c(window).width()/2-b.options.width/2,width:b.options.width}).appendTo("body").css({top:-1.5*b.box.height()}).css({visibility:"visible"}).animate({top:0,opacity:1},this.options.speed,this.options.easing,function(){b.options.onShow.apply(this)});c(window).bind("resize.topbox",function(){b.box.css({left:c(window).width()/2-b.options.width/2,width:b.options.width})});this.options.closeOnEsc&&c(document).bind("keydown.topbox",function(a){27===a.keyCode&&(a.preventDefault(),b.close())});
this.showOverlay();return this},close:function(){if(this.box){if(!1===this.options.beforeClose.apply(this))return this;this.overlay.fadeOut();this.box.animate({top:-1.5*b.box.height(),opacity:0},this.options.speed,this.options.easing,function(){b.clear()});this.options.onClose.apply(this);return this}},confirm:function(a,d,e){e=c.extend({title:"Please confirm",buttons:{Ok:function(){d.apply(b)},Cancel:function(){this.close()}}},e);this.show(a,e)},alert:function(a,b){b=c.extend({title:"Alert",buttons:{Ok:function(){this.close()}}},
b);this.show(a,b)},clear:function(){if(this.box)return this.persist&&(this.persist.appendTo(this.persist.data("tb-persist-parent")),this.persist=!1),this.box.remove(),this.box=null,this.overlay&&this.overlay.hide(),c(window).unbind("resize.topbox"),c(document).unbind("keydown.topbox"),this},setTitle:function(a){if(this.box)return a?this.box.find(".topbox-title").html(a).show():this.box.find(".topbox-title").html(a).hide(),this},setContent:function(a){if(this.box)return"object"===typeof a?(a=a instanceof
jQuery?a:c(a),a.parent().length&&(this.persist=a,this.persist.data("tb-persist-parent",a.parent()))):a="string"===typeof a||"number"===typeof a?c("<div></div>").html(a):c("<div></div>").html("SimpleModal Error: Unsupported data type: "+typeof a),a.appendTo(this.box.find(".topbox-innercontent").html("")),this},showOverlay:function(){this.box&&(this.overlay||(c("#topbox-overlay").length||c("<div>").attr("id","topbox-overlay").css({top:0,left:0,position:"absolute"}).prependTo("body"),this.overlay=c("#topbox-overlay")),
this.overlay.css({width:c(document).width(),height:c(document).height()}).show())}};c.fn.topbox=function(){var a=arguments,b=a[0]?a[0]:{};return this.each(function(){c.topbox.show(this,b)})}})(jQuery);
